tasks:
  - name: api-console
    before: |
      cd /workspace/langchain-flare-pdf-qa-demo
      mkdir .gitpod_logs
      curl -Ls "https://dtsx.io/get-astra-cli" | bash | tee -a /workspace/langchain-flare-pdf-qa-demo.gitpod_logs/astra-cli-install.log
    command: |
      source /home/gitpod/.astra/cli/astra-init.sh
      clear
      astra setup
      DB_NAME=`astra db list -o json | jq -r ' .data[] | select( .V != "") | select( .Status == "ACTIVE" ) | .Name '`
      astra db create-dotenv "${DB_NAME}" -d .
      /workspace/langchain-flare-pdf-qa-demo/scripts/ingest_openai_key.sh /workspace/langchain-flare-pdf-qa-demo/.env
      cd /workspace/langchain-flare-pdf-qa-demo/api
      pip install -r requirements.txt
      uvicorn api:app
      #gp open README.md
  - name: app-console
    openMode: split-right
    before: |
      cd /workspace/langchain-flare-pdf-qa-demo/app
      #nvm install 16.13.0
      #npm install -g npm@latest
      npm install
    command: |
      cd /workspace/langchain-flare-pdf-qa-demo/app
      REACT_APP_API_BASE_URL=`gp url 8000` npm start
ports:
  - port: 3000
    onOpen: open-preview
  - port: 8000
    onOpen: ignore
    visibility: public
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false
